import {e} from './feedback-ui';
import {creditRules} from './credit-rules';
export function communityMap(s:any){
 const toward=Math.max(0,Math.min(4,s.towardNext)),v=s.verification,earned=Math.max(0,v.earned);
 const verification=v.verified?'Verified creator':v.caseId?'Review pending':v.eligible?'Review unlocked':'Verification review';
 return `<section class="cw-panel community-map"><header class="community-map-header"><div><p class="eyebrow">Give feedback. Get discovered.</p><h2>Your community progress</h2></div><div class="credit-balance"><strong>${s.balance}</strong><span>credits available</span></div></header><div class="progress-lanes">
 <section class="progress-lane"><header><h3>Request feedback</h3><strong>${s.balance>=1?'Ready to request':'Earn your first credit'}</strong></header><progress max="1" value="${Math.min(1,Math.max(0,s.balance))}" aria-label="Credit available for a feedback request"></progress><div class="milestone-labels"><span>1 qualifying review</span><strong>1 credit → 1 request</strong></div><details><summary>How do I use credits?</summary><p>A qualifying firsthand review earns one credit. Creator recognition can raise that to 5 or 10 total, with limits. Requests reserve one available credit until feedback arrives; cancel first to return it. A request doesn’t guarantee a response.</p><a href="/dashboard?view=creator">Request from My projects →</a></details></section>
 <section class="progress-lane"><header><h3>Another project slot</h3><strong>${toward} / 5 creators helped</strong></header><progress max="5" value="${toward}" aria-label="Different creators helped toward next project slot"></progress><div class="milestone-labels"><span>${s.used} / ${s.slots} slots used</span><strong>5 creators → +1 slot</strong></div><details><summary>${5-toward} more to unlock · How does this count?</summary><p>Each different creator counts once across your lifetime. Every five unlock another project slot. Bonus and referral credits do not advance this track. Your first slot and existing access are preserved. New listings still require review.</p></details></section>
 <section class="progress-lane"><header><h3>${verification}</h3><strong>${earned} / 50 lifetime credits</strong></header><progress max="50" value="${Math.min(50,earned)}" aria-label="Lifetime credits toward verification review"></progress><div class="milestone-labels"><span>Spending doesn’t reduce this</span><strong>50 → review eligibility</strong></div><details><summary>${v.verified?'Identity reviewed':v.eligible?'Next: identity and ownership review':'What else is required?'}</summary><p>${v.hasPublished?'✓':'○'} An approved, published project. ${v.verified?'✓ Identity and ownership reviewed.':v.caseId?'Your review is pending.':'Identity and project ownership must be reviewed before the badge is awarded.'} Lifetime review rewards and bonuses count; reversed rewards do not. The badge is not a guarantee of product quality or safety.</p><a href="${v.caseId?'/dashboard/help?case='+e(v.caseId):'/dashboard/verification'}">View verification details →</a></details></section>
 </div><a class="primary-button" href="#review-projects">Find a project to review</a>${creditRules}</section>`;
}
