import {randomUUID} from 'node:crypto';
import {e,pageNumber} from './feedback-ui';
export function directComposer(recipient:string,thread=''){
 return `<form class="inline-composer" data-direct-compose action="/api/direct-messages" method="post"><input type="hidden" name="action" value="send"><input type="hidden" name="recipient" value="${e(recipient)}"><input type="hidden" name="thread" value="${e(thread)}"><input type="hidden" name="requestId" value="${randomUUID()}"><div class="compose-field"><label class="visually-hidden" for="direct-${e(thread||recipient)}">Private message</label><textarea id="direct-${e(thread||recipient)}" name="message" rows="2" maxlength="2000" required placeholder="Write a private message…"></textarea><button type="submit" class="send-arrow" aria-label="Send private message" hidden>➤</button></div><p class="cw-meta">Private between participants; no community credits. Moderators may review reported messages.</p><p data-direct-status role="status"></p></form>`;
}
export async function directThread(db:any,user:string,id:string){const r=await db.from('direct_threads').select('id,member_a,member_b').eq('id',id).maybeSingle();if(r.error)throw r.error;return r.data&&[r.data.member_a,r.data.member_b].includes(user)?r.data:null;}
export async function directConversation(db:any,user:string,id:string,url:URL){
 const thread=await directThread(db,user,id);if(!thread)return null;const other=thread.member_a===user?thread.member_b:thread.member_a,page=pageNumber(url.searchParams.get('directPage'));
 const [messages,people,blocks]=await Promise.all([db.from('direct_messages').select('id,sender_id,message,created_at',{count:'exact'}).eq('thread_id',id).order('created_at',{ascending:false}).order('id').range(page*25,page*25+24),db.from('profiles').select('user_id,display_name').in('user_id',[user,other]),db.from('direct_blocks').select('blocker,blocked').or(`and(blocker.eq.${user},blocked.eq.${other}),and(blocker.eq.${other},blocked.eq.${user})`)]);if(messages.error||people.error||blocks.error)throw Error();
 const name=(uid:string)=>people.data.find((p:any)=>p.user_id===uid)?.display_name||'Member',mine=blocks.data.some((b:any)=>b.blocker===user);
 const report=`<details><summary>Report this conversation</summary><form method="post" action="/api/direct-messages"><input type="hidden" name="action" value="report"><input type="hidden" name="thread" value="${id}"><input type="hidden" name="requestId" value="${randomUUID()}"><label>What should we review?<textarea name="reason" required minlength="10" maxlength="1000"></textarea></label><button class="secondary-button">Send report</button></form></details>`;
 return `<section data-conversation-content><h3>Private conversation with ${e(name(other))}</h3><div class="direct-conversation-messages">${[...messages.data].reverse().map((m:any)=>`<article class="cw-reply"><strong>${e(name(m.sender_id))}</strong><p class="cw-message">${e(m.message)}</p><small>${e(new Date(m.created_at).toLocaleString('en-US'))}</small></article>`).join('')}</div><nav class="cw-row">${page?`<a href="/dashboard/messages?direct=${id}&amp;directPage=${page-1}">Newer messages</a>`:''}${(page+1)*25<(messages.count||0)?`<a href="/dashboard/messages?direct=${id}&amp;directPage=${page+1}">Older messages</a>`:''}</nav>${blocks.data.length?'<p>Messaging is unavailable for this conversation.</p>':directComposer('',id)}<details><summary>Conversation options</summary><form method="post" action="/api/direct-messages" data-direct-block><input type="hidden" name="action" value="${mine?'unblock':'block'}"><input type="hidden" name="thread" value="${id}"><button class="secondary-button">${mine?'Unblock':'Block'} this person</button></form>${report}</details>${page===0&&messages.data[0]?`<form data-mark-thread-read action="/api/direct-messages" method="post"><input type="hidden" name="action" value="read"><input type="hidden" name="thread" value="${id}"><input type="hidden" name="seenThrough" value="${e(messages.data[0].created_at)}"></form>`:''}</section>`;
}
