import type { APIRoute } from 'astro';
import { memberContext, workspace, notice, empty } from '../../server/workspace';
import { signIn, e, unavailable } from '../../server/feedback-ui';
import { randomUUID } from 'node:crypto';
const field=(name:string,value:string)=>`<input type="hidden" name="${name}" value="${e(value)}">`;
const start=(action:string,section:string)=>`<form method="post" action="/api/dashboard">${field('action',action)}${field('section',section)}`;
const check=(name:string,label:string,on:boolean)=>`<label class="cw-choice"><input type="checkbox" name="${name}" ${on?'checked':''}>${label}</label>`;
export const GET:APIRoute=async context=>{
 const section=context.params.section||'';
 if(!['overview','notifications','preferences','privacy','help'].includes(section))return new Response('Not found',{status:404});
 try {
  const m=await memberContext(context);if(!m)return signIn('/dashboard/'+section);
  const {db,member,admin}=m;let body=notice(context),title='';
  if(section==='overview'){
   title='Welcome to your dashboard';
   const results=await Promise.all([db.from('projects').select('id',{head:true,count:'exact'}).eq('owner_user_id',member.id),db.from('saved_projects').select('project_slug',{head:true,count:'exact'}).eq('user_id',member.id),db.from('notifications').select('id',{head:true,count:'exact'}).eq('user_id',member.id).is('read_at',null),db.from('support_cases').select('id',{head:true,count:'exact'}).eq('user_id',member.id).neq('status','resolved')]);
   if(results.some(r=>r.error))throw Error();
   body+=`<div class="cw-stat-grid">${results.map((r,i)=>`<a class="cw-panel" href="${['/dashboard?view=creator','/dashboard','/dashboard/notifications','/dashboard/help'][i]}"><strong>${r.count}</strong><span>${['My projects','Saved projects','Unread notifications','Open requests'][i]}</span></a>`).join('')}</div><section class="cw-panel"><h2>Make something worth discovering.</h2><p>Add a project, pick up a draft, or see what people thought after trying your work.</p><div class="cw-row"><a class="primary-button" href="/?listing=settings&new=1">Add a project</a><a class="secondary-button" href="/dashboard?view=creator">Manage my projects</a></div></section>`;
  }else if(section==='preferences'||section==='notifications'){
   const pref=await db.from('account_preferences').select('*').eq('user_id',member.id).maybeSingle();if(pref.error)throw Error();const p=pref.data||{feedback_alerts:true,publication_alerts:true,tips:true,interests:[]};
   title=section==='preferences'?'Your preferences':'Notifications';
   if(section==='preferences')body+=`<section class="cw-panel">${start('preferences',section)}<h2>Make discovery more useful</h2><label for="interests">Topics you care about</label><input id="interests" name="interests" value="${e(p.interests.join(', '))}" maxlength="490" placeholder="Technology, Family life, Creative work"><p class="cw-meta">Separate up to 10 topics with commas. These help order similar project suggestions.</p>${check('tips','Show guidance tips',p.tips)}<p class="cw-meta">Show contextual help while preparing a project. Turn tips back on here at any time.</p><button class="primary-button">Save preferences</button></form></section>`;
   else{
    const page=Math.max(0,Math.min(10000,Math.floor(Number(context.url.searchParams.get('page'))||0)));
    const rows=await db.from('notifications').select('*',{count:'exact'}).eq('user_id',member.id).order('created_at',{ascending:false}).order('id').range(page*25,page*25+24);if(rows.error)throw Error();
    body+=`<section class="cw-panel">${start('alerts',section)}<h2>In-app alerts</h2>${check('feedbackAlerts','New feedback and replies',p.feedback_alerts)}${check('publicationAlerts','Project publication updates',p.publication_alerts)}<p class="cw-meta">Support replies always appear here. Email and push notifications are not enabled.</p><button class="secondary-button">Save alert settings</button></form></section>${start('read-all',section)}<button class="secondary-button">Mark all as read</button></form>${rows.data.map(n=>`<article class="cw-panel"><p class="cw-meta">${n.read_at?'Read':'Unread'} · ${e(new Date(n.created_at).toLocaleDateString('en-US'))}</p><a href="${e(n.href.startsWith('/')&&!n.href.startsWith('//')?n.href:'/dashboard')}">${e(n.title)}</a>${!n.read_at?`${start('read',section)}${field('id',n.id)}<button class="cw-link">Mark as read</button></form>`:''}</article>`).join('')||empty('You’re all caught up. New updates will appear here.')}<nav class="cw-row">${page?`<a href="?page=${page-1}">Previous</a>`:''}${(page+1)*25<(rows.count||0)?`<a href="?page=${page+1}">Next</a>`:''}</nav>`;
   }
  }else if(section==='privacy'){
   title='Privacy & your data';body+=`<section class="cw-panel"><h2>Your public identity</h2><p>You control whether your profile is public. Published projects and public contributions can still show your public name.</p><a href="/dashboard/profile">Manage public profile</a></section><section class="cw-panel"><h2>Download your data</h2><p>Export your profile, projects, saved items, preferences, contributions, and support requests as a JSON file.</p><a class="secondary-button" href="/api/account-export">Download my data</a></section><section class="cw-panel"><h2>Optional analytics</h2><p>Analytics is off unless you choose to allow it.</p><button class="secondary-button" data-analytics-settings>Change analytics preference</button><script src="/analytics.js" defer></script></section><section class="cw-panel"><h2>Account deletion</h2><p>Request deletion or check a pending request in your account settings.</p><a href="/dashboard/security">Account & security</a></section><p><a href="/privacy">Read our privacy notice</a></p>`;
  }else{
   title='Help & contact';const id=context.url.searchParams.get('case');
   if(id&&/^[0-9a-f-]{36}$/.test(id)){
    const r=await db.from('support_cases').select('*').eq('id',id).eq('user_id',member.id).maybeSingle();if(r.error)throw Error();if(!r.data)return new Response('Not found',{status:404});const c=r.data;
    const messages=await db.from('support_messages').select('message,is_staff,created_at').eq('case_id',id).order('created_at');if(messages.error)throw Error();
    body+=`<p><a href="/dashboard/help">← All requests</a></p><section class="cw-panel"><p class="cw-meta">${e(c.kind)} · ${e(c.status)}</p><h2>${e(c.subject)}</h2><p class="cw-message">${e(c.message)}</p></section>${messages.data.map(r=>`<section class="cw-panel"><strong>${r.is_staff?'CreatorWorks support':'You'}</strong><p class="cw-message">${e(r.message)}</p></section>`).join('')}<section class="cw-panel">${start('case-reply','help')}${field('id',id)}${field('revision',String(c.revision))}${field('request',randomUUID())}<label for="message">Add a reply</label><textarea name="message" id="message" minlength="1" maxlength="4000" required></textarea><button class="primary-button">Send reply</button></form></section>`;
   }else{
    const rows=await db.from('support_cases').select('id,subject,status,created_at').eq('user_id',member.id).order('created_at',{ascending:false}).limit(100);if(rows.error)throw Error();
    body+=`<section class="cw-panel"><h2>Quick answers</h2><details><summary>Where is my project?</summary><p>Open My projects to continue drafts or view publication status. A draft stays private until you submit it and it is approved.</p></details><details><summary>How do I update a project?</summary><p>Choose Edit in My projects. Changes to public content return the listing to review.</p></details><details><summary>How do I report a problem?</summary><p>Choose a request type below. Include the project name or link and what happened. Never send passwords or payment information.</p></details></section><section class="cw-panel"><h2>Contact CreatorWorks</h2>${start('case-create','help')}${field('id',randomUUID())}<label for="kind">I need help with</label><select name="kind" id="kind">${[['support','General support'],['report','Report abuse or a project'],['copyright','Copyright concern'],['appeal','Appeal a moderation decision'],['verification','Creator verification']].map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select><label for="subject">Subject</label><input name="subject" id="subject" minlength="3" maxlength="120" required><label for="project">Project identifier (optional)</label><input name="project" id="project" pattern="[a-z0-9-]{1,80}" maxlength="80" placeholder="The project’s URL name"><label for="message">How can we help?</label><textarea id="message" name="message" minlength="10" maxlength="4000" required></textarea><p class="cw-meta">For copyright concerns, identify your work, the project involved, and your authority to report it. This starts a review; it is not by itself a complete statutory notice. Replies appear here and in Notifications.</p><button class="primary-button">Send request</button></form></section><h2>My requests</h2>${rows.data.map(r=>`<article class="cw-panel"><a href="?case=${r.id}">${e(r.subject)}</a><p class="cw-meta">${e(r.status)} · ${e(new Date(r.created_at).toLocaleDateString('en-US'))}</p></article>`).join('')||empty('No requests yet.')}`;
   }
  }
  return workspace(title,body,section,admin);
 }catch{return unavailable();}
};
