import type {APIRoute} from 'astro';
import {memberContext} from '../../server/workspace';
import {surface,e,signIn,unavailable} from '../../server/feedback-ui';
import {readBuilds} from '../../server/builds';
export const GET:APIRoute=async context=>{
 try{
  const m=await memberContext(context);if(!m)return signIn('/dashboard/builds?project='+encodeURIComponent(context.url.searchParams.get('project')||''));
  const r=await m.db.from('projects').select('id,slug,title,listing_status').eq('slug',context.url.searchParams.get('project')||'').eq('owner_user_id',m.member.id).maybeSingle();
  if(r.error)throw r.error;if(!r.data)return surface('Project not found','<h1>Project not found</h1>','creator',404,m.admin);
  const p=r.data,s=await readBuilds(m.db,p.id),active=s.builds.find(b=>b.id===s.active);
  const fields=`<input type="hidden" name="project" value="${e(p.slug)}"><input type="hidden" name="revision" value="${s.revision}">`;
  return surface('Project builds',`<header><p class="eyebrow">Project settings</p><h1>Builds & updates</h1><p>${e(p.title)}</p><a href="/?listing=settings&project=${e(p.slug)}">Back to project settings</a></header>${context.url.searchParams.has('saved')?'<p role="status" class="cw-notice">Build settings saved.</p>':''}<section class="cw-panel"><h2>Active build: ${e(active?.version||'Not selected')}</h2><p>${e(active?.notes||'Add your first build below, then select it here.')}</p><p>Changing the active build announces its improvements to people who saved this project and enabled project updates. This records your release on TryMyBuild; deploy it to your project’s website first.</p>${s.builds.length&&p.listing_status==='published'?`<form method="post" action="/api/builds">${fields}<input type="hidden" name="action" value="activate"><label for="active-build">Which build is live?</label><select id="active-build" name="build" required>${s.builds.map(b=>`<option value="${e(b.id)}" ${b.id===s.active?'selected':''}>${e(b.version)}</option>`).join('')}</select><p class="cw-meta">Selecting the current build again sends no duplicate update.</p><button class="primary-button">Set active build & notify followers</button></form>`:'<p>Publish your project and add a build to enable announcements.</p>'}</section><section class="cw-panel"><h2>Add a build</h2><form method="post" action="/api/builds">${fields}<input type="hidden" name="action" value="create"><label for="build-version">Build name or version</label><input id="build-version" name="version" maxlength="40" placeholder="e.g. 1.2.0" required><label for="build-notes">What improved?</label><textarea id="build-notes" name="notes" minlength="10" maxlength="300" required placeholder="Describe the fixes or improvements people can try." aria-describedby="build-note-help"></textarea><p id="build-note-help" class="cw-meta">10–300 characters. These notes become public when you activate this build. Saving alone does not announce an unfinished build.</p><button class="secondary-button">Save build</button></form></section><section><h2>Build history</h2>${[...s.builds].reverse().map(b=>`<article class="cw-panel"><h3>${e(b.version)} ${b.id===s.active?'· Active':''}</h3><p>${e(b.notes)}</p><p class="cw-meta">${s.events.some(v=>v.buildId===b.id)?'Released':'Not announced'} · Added ${e(new Date(b.createdAt).toLocaleDateString('en-US'))}</p></article>`).join('')||'<p>No builds yet.</p>'}</section>`,'creator',200,m.admin);
 }catch{return unavailable();}
};
