import type {APIRoute} from 'astro';
import {randomUUID} from 'node:crypto';
import {memberContext,workspace,notice} from '../../server/workspace';
import {signIn,e,unavailable} from '../../server/feedback-ui';
import {creditSummary,feedbackQueue} from '../../server/community-credits';
export const GET:APIRoute=async context=>{
 try{const m=await memberContext(context);if(!m)return signIn('/dashboard/community');const [s,queue]=await Promise.all([creditSummary(m.db,m.member.id),feedbackQueue(m.db,m.member.id)]);
  const eligible=s.projects.filter((p:any)=>p.listing_status==='published'),open=new Set(s.requests.filter((r:any)=>r.status==='queued').map((r:any)=>r.project_slug));
  const request=(p:any)=>`<form method="post" action="/api/community-credits"><input type="hidden" name="id" value="${randomUUID()}"><input type="hidden" name="slug" value="${e(p.slug)}"><input type="hidden" name="action" value="create"><button class="secondary-button" ${s.balance<1||open.has(p.slug)?'disabled':''}>${open.has(p.slug)?'Waiting for feedback':'Request feedback · 1 credit'}</button></form>`;
  const body=`${notice(context)}<section class="cw-panel community-progress"><p class="eyebrow">Give feedback. Get discovered.</p><h2>Your community progress</h2><div class="cw-stat-grid"><div><strong>${s.balance}</strong><span>feedback credits available</span></div><div><strong>${s.towardNext} / 5</strong><span>projects helped toward your next slot</span></div><div><strong>${s.used} / ${s.slots}</strong><span>published project slots used</span></div></div><p>Give specific feedback on five different creators’ projects to unlock another project slot. Each qualifying response earns one credit, which can place one of your published projects in the feedback queue.</p><p class="cw-meta">A credit requests community attention; it does not guarantee a response or deadline. Drafts and build updates remain available without another slot.</p></section><section><h2>Projects asking for your perspective</h2><p>Choose something you can meaningfully try. Feedback must contain 7–150 words and discuss the project respectfully.</p>${queue.map((x:any)=>`<article class="cw-panel"><p class="eyebrow">${e(x.project.category)}</p><h3>${e(x.project.title)}</h3><p>${e(x.project.summary)}</p><a class="primary-button" href="/projects/${e(x.project_slug)}">Try this project</a> <a class="secondary-button" href="/tell/${e(x.project_slug)}">Give feedback</a></article>`).join('')||'<p class="cw-panel">No projects are waiting right now. Browse the catalog and help any project that interests you.</p>'}</section><section><h2>Request feedback for your work</h2>${eligible.map((p:any)=>`<article class="cw-panel"><h3>${e(p.title)}</h3>${request(p)}${open.has(p.slug)?`<form method="post" action="/api/community-credits"><input type="hidden" name="id" value="${e(s.requests.find((r:any)=>r.project_slug===p.slug&&r.status==='queued').id)}"><input type="hidden" name="slug" value="${e(p.slug)}"><input type="hidden" name="action" value="cancel"><button class="cw-link">Cancel and return credit</button></form>`:''}</article>`).join('')||'<p class="cw-panel">Publish a project to request feedback.</p>'}</section><section><h2>How your contributions were counted</h2>${s.qualifications.slice(0,10).map((q:any)=>`<article class="cw-panel"><strong>${e(q.project_slug)}</strong><p>${e(q.status)} · ${e(q.reason)}</p></article>`).join('')||'<p class="cw-panel">Your qualifying project feedback will appear here.</p>'}<p><a href="/community-guidelines">Read the Community Guidelines</a></p></section>`;
  return workspace('Community credits',body,'community',m.admin);
 }catch{return unavailable();}
};
