import type {APIRoute} from 'astro';
import {adminUser} from '../../server/admin';
import {database} from '../../server/database';
import {surface,e,unavailable} from '../../server/feedback-ui';
export const GET:APIRoute=async context=>{
 const user=await adminUser(context);if(!user)return surface('Private administration','<h1>Administrator access required.</h1>','',403);
 try{const db=database(),kind=context.url.searchParams.get('kind')==='daily'?'daily':'credits';let html='<a href="/admin">← Administration</a><h1>Community review</h1><nav class="cw-row"><a href="?kind=credits">Credit qualifications</a><a href="?kind=daily">Daily discussion</a></nav>';
  if(context.url.searchParams.has('saved'))html+='<p class="cw-notice" role="status">Decision saved.</p>';if(context.url.searchParams.has('error'))html+='<p class="cw-notice" role="alert">That decision was not saved. Reload and try again.</p>';
  if(kind==='credits'){
   const r=await db.from('feedback_qualifications').select('feedback_id,user_id,project_slug,word_count,status,reason,revision,updated_at').eq('status','pending').order('updated_at').limit(100);if(r.error)throw r.error;
   const ids=r.data.map((x:any)=>x.feedback_id),feedback=ids.length?await db.from('creator_feedback').select('id,message,helpful,visibility').in('id',ids):{data:[],error:null};if(feedback.error)throw feedback.error;
   html+='<p>Review feedback that was not automatically credited because it was repetitive or did not describe a firsthand attempt.</p>'+r.data.map((q:any)=>{const f=feedback.data.find((x:any)=>x.id===q.feedback_id);return `<article class="cw-panel"><h2>${e(q.project_slug)} · ${q.word_count} words</h2><p>${e(f?.message||'Feedback unavailable')}</p><p class="cw-meta">${e(q.reason)} · ${e(f?.visibility||'')}</p><form method="post" action="/api/admin/community-review"><input type="hidden" name="kind" value="credit"><input type="hidden" name="id" value="${e(q.feedback_id)}"><input type="hidden" name="revision" value="${q.revision}"><label>Decision<select name="status"><option value="qualified">Award credit</option><option value="rejected">Do not award</option></select></label><label>Reason<input name="reason" minlength="3" maxlength="300" required></label><button class="primary-button">Save decision</button></form></article>`;}).join('')||'<p class="cw-panel">No credit qualifications need review.</p>';
  }else{
   const r=await db.from('daily_discussion_comments').select('*').eq('moderation_status','pending').order('created_at').limit(100);if(r.error)throw r.error;const ids=[...new Set(r.data.map((x:any)=>x.user_id))],profiles=ids.length?await db.from('profiles').select('user_id,display_name').in('user_id',ids):{data:[],error:null};if(profiles.error)throw profiles.error;
   html+='<p>Publishing displays the response and member identity in its category conversation or original daily discussion.</p>'+r.data.map((x:any)=>`<article class="cw-panel"><h2>${e(profiles.data.find((p:any)=>p.user_id===x.user_id)?.display_name||'Member')}</h2><p>${e(x.message)}</p><p class="cw-meta">${e(x.day_key)} · ${x.category?e(x.category):`Daily question ${x.tip_index+1}`}</p><form method="post" action="/api/admin/community-review"><input type="hidden" name="kind" value="daily"><input type="hidden" name="id" value="${e(x.id)}"><input type="hidden" name="previous" value="${e(x.moderation_status)}"><label>Decision<select name="status"><option value="published">Publish</option><option value="hidden">Hide</option></select></label><label>Reason<input name="reason" minlength="3" maxlength="300" required></label><button class="primary-button">Save decision</button></form></article>`).join('')||'<p class="cw-panel">No daily responses need review.</p>';
  }
  return surface('Community review',html,'',200,true);
 }catch{return unavailable();}
};
