import type { APIRoute } from 'astro';
import { memberContext,workspace } from '../../server/workspace';
import { e,unavailable } from '../../server/feedback-ui';
export const GET:APIRoute=async context=>{
 try{
  const m=await memberContext(context);if(!m?.admin)return new Response('Forbidden',{status:403});
  const r=await m.db.from('projects').select('*').eq('slug',context.url.searchParams.get('slug')||'').maybeSingle();if(r.error)throw r.error;if(!r.data)return new Response('Not found',{status:404});const p=r.data;
  const fields=[['category','Category'],['summary','Summary'],['headline','What it does'],['help_text','How it helps'],['first_try','First feature to try'],['external_url','Project URL'],['video_url','Video URL'],['listing_status','Publication status'],['owner_user_id','Owner member ID']];
  const body=`<p><a href="/admin?section=projects">← All projects</a></p><section class="cw-panel">${fields.map(([key,label])=>`<h2>${label}</h2><p class="cw-message">${e(p[key]||'Not supplied')}</p>`).join('')}${p.video_url?`<a class="secondary-button" href="${e(p.video_url)}" target="_blank" rel="noopener noreferrer">Review video ↗</a>`:''}${p.preview_public_url?`<p><img src="${e(p.preview_public_url)}" alt="Project preview" style="max-width:100%;max-height:420px"></p>`:''}</section><section class="cw-panel"><h2>Publication decision</h2><form method="post" action="/api/admin/project-review"><input type="hidden" name="id" value="${p.id}"><input type="hidden" name="previous" value="${e(p.listing_status)}"><input type="hidden" name="version" value="${p.lock_version}"><label>Status<select name="status"><option value="published">Publish</option><option value="unpublished">Unpublish</option><option value="draft">Return to draft</option><option value="in_review">Return to review</option></select></label><label>Reason<input name="reason" minlength="3" maxlength="300" required></label><label class="cw-choice"><input type="checkbox" name="confirm" value="yes" required>I reviewed all content and confirm this decision.</label><button class="primary-button">Apply publication decision</button></form></section>${!p.is_studio?`<section class="cw-panel"><h2>Correct project ownership</h2><p>Use only after confirming control with both affected parties. This changes who can edit the project and read its private creator feedback. The project returns to review.</p><form method="post" action="/api/admin/manage"><input type="hidden" name="action" value="transfer"><input type="hidden" name="id" value="${p.id}"><input type="hidden" name="version" value="${p.lock_version}"><label>New owner’s member ID<input name="owner" pattern="[0-9a-f-]{36}" required></label><label>Evidence and reason<input name="reason" minlength="3" maxlength="300" required></label><label class="cw-choice"><input type="checkbox" name="confirm" value="yes" required>I verified this transfer with the affected parties.</label><button class="secondary-button">Correct ownership</button></form></section>`:'<p>In-house project ownership is protected.</p>'}`;
  return workspace(p.title,body,'overview',true);
 }catch{return unavailable();}
};
